### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by Slashgear** [PolytechLyon/isi3-tp2-visiteur-fondacci-frazer-tp2#1]
Dans l'etat ça vaut 0 sans le rapport.

ça fait 2 fois

**Comment by Pheoda** [comment]
Il y avait un rapport pour le premier. Quelle était la première fois ?

**Comment by Slashgear** [comment]
Désolé j'ai confondu deux groupes sorry 🙏 

Par contre pour le premier TP vous n'avez, semblerait-il pas pris les retours, c'est voulu ?
Quand vous jugez avoir pris les retours d'un TP. Prévenez moi avec un petit message dans l'issue associée.

Pour ce TP en tout cas je ne peux toujours pas noter.

**Comment by Pheoda** [comment]
Pas de souci, nous allons rédiger le rapport cet après midi, en essayant de revoir les corrections du TP1. On préviendra sans faute !

**Comment by Pheoda** [comment]
Le TP est terminé et le rapport a été rédigé

**Comment by Slashgear** [comment]
- [ ] on range les class en packages (en minuscule svp)
- [ ] Votre gestion de la priorité vous permet-elle de représenter 7*2+3 en respectant la priorité de la multiplication.
- [ ] On fait le ménage des vieilles méthodes opG et opD qui sont pas vraiment claires à la relecture ?

**Comment by Pheoda** [comment]
Bonjour,

-  j'ai effectué les corrections en rangeant les classes en 2 packages (peut-être en fallait-il plus ?). 

- j'ai refactorer quelques noms de variables qui n'étaient en effet pas très clairs. 

- pour ce qui est de l'opération 7 * 2 + 3, le résultat de notre code renvoie bien ((7*2) + 3)

```
prefix:
+*723
infixe:
7*2+3
calcul valeur: 17

calcul hauteur: 3

postfixe:
72*3+
priorite:
((7*2)+3)
```

**Comment by Slashgear** [comment]
Ok
